### ISSUE TITLE
Support Customer Orders

### ISSUE THREAD

**Issue by azelenovsky** [stern-devops-2020-inventory/inventory#13]
As a User, 
I need the ability to remove products from inventory to place into a shopping cart.
So that I can ensure I do not run out of inventory.

Assumptions:

    The SKU of the product and quantity is passed to the API 
    A call to POST /inventory should update inventory in accordance to the value passed (positive to add, negative    to delete)
    Inventory cannot be negative.

Acceptance Criteria:

When I call POST /Inventory 
I should see a JSON object with updated product inventory levels
Inventory should be updated accordingly 
Cannot go negative.

**Comment by npd271** [comment]
Andrey
