### ISSUE TITLE
CREATE vagrant file with depedencies

### ISSUE THREAD

**Issue by azelenovsky** [stern-devops-2020-inventory/inventory#2]
As a Developer
I need the ability to have a vagrant file bring up all of my dependencies 
So that I can do development and commit to github.

Assumptions:

We will be following the same stack as Professor Rofrano.

Acceptance Criteria:

Given that a team member opens the terminal at the project's directory
When I run vagrant up
Then it loads the vm machine with the correct dependencies

**Comment by npd271** [comment]
Andrey

**Comment by azelenovsky** [comment]
In order for the team to start developing, a vagrant file with all the dependencies needs to be created.

**Comment by Maria-Bruno** [comment]
I closed this issue because the actual task was covered by "create skeleton project" issue #20
