### ISSUE TITLE
Update README to include Travis CI

### ISSUE THREAD

**Issue by azelenovsky** [stern-devops-2020-inventory/inventory#22]
**As a** ...  developer
**I need** ...  to keep the README.md file up to date
**So that** ...  instructions are provided to potential users and Travis CI badge alerts potential coders to broken code

on:
Travis CI badge
what calls are available,
what inputs are expected,
how to run and test the code so that users know how it works.

**Assumptions:** 
* ... Every sprint must have a Travis CI badge and has functionality updates that need to be reflected in the README file.

**Acceptance Criteria:**
```
Given ... A new release,
When ... a sprint concludes
Then ... the README file should include a Travis CI badge and reflect the current status of the project.
```

**Comment by Maria-Bruno** [comment]
Good example, for reference: https://github.com/DevOps-Promo/promotions/blob/master/README.md

**Comment by Maria-Bruno** [comment]
I'm interested in working on this one

**Comment by Maria-Bruno** [comment]
Sorry for not following Agile etiquette but this issue turned out to be directly connect to the initial setup of Travis (it was all part of the same lab so I had to do all the steps at once. I re-assigned this issue to me and can move it along once the other Travis issue is completed.
