### ISSUE TITLE
LIST all inventory items

### ISSUE THREAD

**Issue by Maria-Bruno** [stern-devops-2020-inventory/inventory#4]
**As an** inventory manager
**I need to** list my inventory levels
**So that I can** so I can see a full list of what is in inventory

**Assumptions:**
* Request will look for parameters to determine scope of response (e.g. timeframe, product type, etc.)
* If no parameters are included, default response to returning all products
* Handle errors elegantly (e.g. if request is invalid, print lines that indicate to API user how to correctly use the API)

**Acceptance Criteria:**
```
Given a request to list all products
When I send a get request to /inventory
Then the API returns a response with all inventory fields in the database
```

**Comment by npd271** [comment]
Maria

**Comment by Maria-Bruno** [comment]
**As an** inventory manager
**I need to** understand when inventory levels are low
**So that I can** reorder stock levels 

**Assumptions:**

All inventory levels are updated in the database when a new product is removed from or added to the actual inventory
There is a relational database between products organized by Product ID
We have a field that indicates the critical inventory level that signals when it's time to restock


Acceptance Criteria:

Given an existing inventory database 

When an inventory product level hits the critical restock level
Then the system would post an update alerting the inventory manager that it is time to reorder

**Comment by azelenovsky** [comment]
I think we need to park the alert functionality and just stick with List All (like pets example)

**Comment by azelenovsky** [comment]
I've updated the title, but we need to create an additional story before updating the description to not have Alert functionality

**Comment by Maria-Bruno** [comment]
Updated the story to reflect the new functionality that this issue will meet
