### ISSUE TITLE
Integrate Pull Requests with Slack Channel

### ISSUE THREAD

**Issue by azelenovsky** [stern-devops-2020-inventory/inventory#46]
**As a** developer
**I need** Pull requests integrated with my team's slack channel  
**So that** everyone is notified when a pull request occurs.

**Assumptions:** 
* Travis CI is setup

**Acceptance Criteria:**
```
Given new code development occurs
When a developer creates a pull request occurs
Then the team's slack channel is notified.
```

**Comment by Maria-Bruno** [comment]
Closed it to see if we'd get a notification in Slack. I didn't get one so I'm reopening to work on this.

**Comment by Maria-Bruno** [comment]
Testing Slack integration
