### ISSUE TITLE
Create IBM Cloud Foundry metadata files

### ISSUE THREAD

**Issue by npd271** [stern-devops-2020-inventory/inventory#51]
**As a** ...  Developer
**I need** ...  metadata files 
**So that** ...  IBM will know how to deploy inventory application

**Assumptions:** 
* ...IBM Foundry metadata files are necessary for successful deployment

**Acceptance Criteria:**
```
Given ...Metadata files stored in IBM Foundry
When ...application is deployed
Then ...all of the files run successfully 
```

**Comment by Maria-Bruno** [comment]
I'm interested in working on this one
