### ISSUE TITLE
Obtain DB Credentials from VCAP_Services

### ISSUE THREAD

**Issue by azelenovsky** [stern-devops-2020-inventory/inventory#54]
**As a** Product Manager
**I need** my application to leverage environment variables
**So that** it can be transferred between environments without conflicts

**Assumptions:** 
* VCAP_Services are present

**Acceptance Criteria:**
```
Given the application running in the cloud
When a database request is made
Then VCAP_SERVICES env variable to used to get the database credentials
```

Modify your application to get the database credentials from the VCAP_SERVICES environment variable if you are using an IBM Cloud database like Cloudant or IBM DB2, or DATABASE_URI if you are using a 3rd party database like PostgreSQL (from ElephantSQL.com). (hint: see models.py in lab-bluemix-cf for an example)

**Comment by Maria-Bruno** [comment]
I'm interested in working on this one
