### ISSUE TITLE
Move Stories through ZenHub pipeline as you go (like homework #1)

### ISSUE THREAD

**Issue by atb459** [stern-devops-2020-inventory/inventory#68]
**As a** developer
**I need** to advance the stories through the pipeline
**So that** each team member is aware of our overall progress

**Assumptions:** 
* Each team member will advance their stories

**Acceptance Criteria:**
```
Given a story is completed
When the story is complete
Then we will move the story through the ZenHub pipeline
```

**Comment by Maria-Bruno** [comment]
I think we can just move this to 'closed'
