### ISSUE TITLE
Write Stories (as Github Issues) to plan the work needed to create the test cases and add them to your Sprint Backlog.

### ISSUE THREAD

**Issue by atb459** [stern-devops-2020-inventory/inventory#69]
**As a** developer
**I need** to write stories as issues
**So that** our team can efficiently work together.

**Assumptions:** 
* If the stories are written out as issues all developers will have a clear understanding as to what needs to be done.

**Acceptance Criteria:**
```
Given the developers write the stories as issues
When the team meets for the grooming session
Then the issues will be written and the team can execute
```

**Comment by Maria-Bruno** [comment]
I think we can just move this to 'closed'
